/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatlichsieuamthaiRouteImport } from './routes/datlichsieuamthai'
import { Route as DemoDashboardRouteImport } from './routes/demo-dashboard'
import { Route as AuthenticatedQuanLyRouteImport } from './routes/_authenticated/quan-ly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatlichsieuamthaiRoute = DatlichsieuamthaiRouteImport.update({
  id: '/datlichsieuamthai',
  path: '/datlichsieuamthai',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo-dashboard',
  path: '/demo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuanLyRoute = AuthenticatedQuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datlichsieuamthai': typeof DatlichsieuamthaiRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/quan-ly': typeof AuthenticatedQuanLyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datlichsieuamthai': typeof DatlichsieuamthaiRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/quan-ly': typeof AuthenticatedQuanLyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datlichsieuamthai': typeof DatlichsieuamthaiRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/_authenticated/quan-ly': typeof AuthenticatedQuanLyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/datlichsieuamthai' | '/demo-dashboard' | '/quan-ly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/datlichsieuamthai' | '/demo-dashboard' | '/quan-ly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datlichsieuamthai'
    | '/demo-dashboard'
    | '/_authenticated/quan-ly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatlichsieuamthaiRoute: typeof DatlichsieuamthaiRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datlichsieuamthai': {
      id: '/datlichsieuamthai'
      path: '/datlichsieuamthai'
      fullPath: '/datlichsieuamthai'
      preLoaderRoute: typeof DatlichsieuamthaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-dashboard': {
      id: '/demo-dashboard'
      path: '/demo-dashboard'
      fullPath: '/demo-dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quan-ly': {
      id: '/_authenticated/quan-ly'
      path: '/quan-ly'
      fullPath: '/quan-ly'
      preLoaderRoute: typeof AuthenticatedQuanLyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedQuanLyRoute: typeof AuthenticatedQuanLyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedQuanLyRoute: AuthenticatedQuanLyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatlichsieuamthaiRoute: DatlichsieuamthaiRoute,
  DemoDashboardRoute: DemoDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
